const data = [
    {
      id: 1,
      userDetails: "John Doe",
      emailAddress: "johndoe@example.com",
      password: "password123",
      dateCreated: "2022-01-01",
      lastLogin: "2022-01-02",
      status: "active",
    },
    {
      id: 2,
      userDetails: "Jane Doe",
      emailAddress: "janedoe@example.com",
      password: "password456",
      dateCreated: "2022-01-03",
      lastLogin: "2022-01-04",
      status: "inactive",
    },
    {
      id: 3,
      userDetails: "Jin Doe",
      emailAddress: "janedoe@example.com",
      password: "password789",
      dateCreated: "2021-01-09",
      lastLogin: "2022-02-14",
      status: "inactive",
    },
    {
      id: 4,
      userDetails: "Jahn Doe",
      emailAddress: "janedoe@example.com",
      password: "password987",
      dateCreated: "2022-01-07",
      lastLogin: "2022-02-28",
      status: "active",
    },
    {
        id: 5,
        userDetails: "John Doe",
        emailAddress: "johndoe@example.com",
        password: "password123",
        dateCreated: "2022-01-01",
        lastLogin: "2022-01-02",
        status: "active",
      },
      {
        id: 6,
        userDetails: "Jane Doe",
        emailAddress: "janedoe@example.com",
        password: "password456",
        dateCreated: "2022-01-03",
        lastLogin: "2022-01-04",
        status: "inactive",
      },
      {
        id: 7,
        userDetails: "Jin Doe",
        emailAddress: "janedoe@example.com",
        password: "password789",
        dateCreated: "2021-01-09",
        lastLogin: "2022-02-14",
        status: "inactive",
      },
      {
        id: 8,
        userDetails: "Jahn Doe",
        emailAddress: "janedoe@example.com",
        password: "password987",
        dateCreated: "2022-01-07",
        lastLogin: "2022-02-28",
        status: "active",
      },
      {
        id: 9,
        userDetails: "John Doe",
        emailAddress: "johndoe@example.com",
        password: "password123",
        dateCreated: "2022-01-01",
        lastLogin: "2022-01-02",
        status: "active",
      },
      {
        id: 10,
        userDetails: "Jane Doe",
        emailAddress: "janedoe@example.com",
        password: "password456",
        dateCreated: "2022-01-03",
        lastLogin: "2022-01-04",
        status: "inactive",
      },
      {
        id: 11,
        userDetails: "Jin Doe",
        emailAddress: "janedoe@example.com",
        password: "password789",
        dateCreated: "2021-01-09",
        lastLogin: "2022-02-14",
        status: "inactive",
      },
      {
        id: 12,
        userDetails: "Jahn Doe",
        emailAddress: "janedoe@example.com",
        password: "password987",
        dateCreated: "2022-01-07",
        lastLogin: "2022-02-28",
        status: "active",
      },
      {
        id: 13,
        userDetails: "Jane Doe",
        emailAddress: "janedoe@example.com",
        password: "password456",
        dateCreated: "2022-01-03",
        lastLogin: "2022-01-04",
        status: "inactive",
      },
      {
        id: 14,
        userDetails: "Jin Doe",
        emailAddress: "janedoe@example.com",
        password: "password789",
        dateCreated: "2021-01-09",
        lastLogin: "2022-02-14",
        status: "inactive",
      },
      {
        id: 15,
        userDetails: "Jahn Doe",
        emailAddress: "janedoe@example.com",
        password: "password987",
        dateCreated: "2022-01-07",
        lastLogin: "2022-02-28",
        status: "active",
      },
      {
        id: 16,
        userDetails: "John Doe",
        emailAddress: "johndoe@example.com",
        password: "password123",
        dateCreated: "2022-01-01",
        lastLogin: "2022-01-02",
        status: "active",
      },
      {
        id: 18,
        userDetails: "Jane Doe",
        emailAddress: "janedoe@example.com",
        password: "password456",
        dateCreated: "2022-01-03",
        lastLogin: "2022-01-04",
        status: "inactive",
      },
      {
        id: 19,
        userDetails: "Jin Doe",
        emailAddress: "janedoe@example.com",
        password: "password789",
        dateCreated: "2021-01-09",
        lastLogin: "2022-02-14",
        status: "inactive",
      },
      {
        id: 20,
        userDetails: "Jahn Doe",
        emailAddress: "janedoe@example.com",
        password: "password987",
        dateCreated: "2022-01-07",
        lastLogin: "2022-02-28",
        status: "active",
      },
      {
        id: 21,
        userDetails: "John Doe",
        emailAddress: "johndoe@example.com",
        password: "password123",
        dateCreated: "2022-01-01",
        lastLogin: "2022-01-02",
        status: "active",
      },
      {
        id: 22,
        userDetails: "Jane Doe",
        emailAddress: "janedoe@example.com",
        password: "password456",
        dateCreated: "2022-01-03",
        lastLogin: "2022-01-04",
        status: "inactive",
      },
      {
        id: 23,
        userDetails: "Jin Doe",
        emailAddress: "janedoe@example.com",
        password: "password789",
        dateCreated: "2021-01-09",
        lastLogin: "2022-02-14",
        status: "inactive",
      },
      {
        id: 24,
        userDetails: "Jahn Doe",
        emailAddress: "janedoe@example.com",
        password: "password987",
        dateCreated: "2022-01-07",
        lastLogin: "2022-02-28",
        status: "active",
      },
      {
        id: 25,
        userDetails: "John Doe",
        emailAddress: "johndoe@example.com",
        password: "password123",
        dateCreated: "2022-01-01",
        lastLogin: "2022-01-02",
        status: "active",
      },
      {
        id: 26,
        userDetails: "Jane Doe",
        emailAddress: "janedoe@example.com",
        password: "password456",
        dateCreated: "2022-01-03",
        lastLogin: "2022-01-04",
        status: "inactive",
      },
      {
        id: 27,
        userDetails: "Jin Doe",
        emailAddress: "janedoe@example.com",
        password: "password789",
        dateCreated: "2021-01-09",
        lastLogin: "2022-02-14",
        status: "inactive",
      },
      {
        id: 28,
        userDetails: "Jahn Doe",
        emailAddress: "janedoe@example.com",
        password: "password987",
        dateCreated: "2022-01-07",
        lastLogin: "2022-02-28",
        status: "active",
      },
      {
        id: 29,
        userDetails: "John Doe",
        emailAddress: "johndoe@example.com",
        password: "password123",
        dateCreated: "2022-01-01",
        lastLogin: "2022-01-02",
        status: "active",
      },
      {
        id: 30,
        userDetails: "Jane Doe",
        emailAddress: "janedoe@example.com",
        password: "password456",
        dateCreated: "2022-01-03",
        lastLogin: "2022-01-04",
        status: "inactive",
      },


  ];

  export default data;